name: flutter_ui_food_delivery_app
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.0.0-122.0.dev <4.0.0'

dependencies:
  bloc_pattern: ^3.0.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  http: ^1.1.0
  rive: ^0.11.17
  address_search_field: ^5.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/images/
    - assets/anim/
    - assets/icons/
    - assets/fonts/
    - assets/images/foods/
    - assets/

  fonts:
    - family: SF Pro Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf

  uses-material-design: true
